server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

#数据源
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/springboot_demo01
    username : root
    password : 1234
    driverClassName : com.mysql.jdbc.Driver

#pagehelper分页插件不同数据库只需修改elperDialect即可
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql



